### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by larebsyed** [ekaschalk/aplig#1]
I am trying to get this working with my setup but I am unable to do so.

I would also like to contribute to this project, if any help is needed.

**Comment by ekaschalk** [comment]
Hi thanks for the interest.

The repo is still in flux - but it should be working.

Try to see if you can get the tests to execute:

run `cask install` in the project root
Then run `cask exec buttercup -L .` and see if the tests pass.

**Comment by larebsyed** [comment]
Actually, I didn't yet download the repo, I just pulled the repo as a package into my emacs. But I am unable to get ligatures to show.

**Comment by ekaschalk** [comment]
Did you look at `nt-dev`? Try requiring it - and running `nt-dev--switch-to-test-buffer` and `nt-dev--switch-to-screenshot-buffer`.  There is a bit more setup than just `nt-enable` at the moment.
